kind: persistentVolume
apiVersion: v1
metadata:
  name: local-vol
  labals:
    app: local
specs:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  persistenetVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
